#!/usr/bin/env bash
set -euo pipefail

# W3C DTCG Design Token Builder
# Reads tokens/tokens.json and generates:
#   - tokens/outputs/tokens.css        (CSS custom properties in :root {})
#   - tokens/outputs/tailwind-theme.css (Tailwind v4 @theme {} block)
# Also verifies WCAG AA contrast for key foreground/background pairs.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOKENS_FILE="$SCRIPT_DIR/tokens.json"
OUTPUT_DIR="$SCRIPT_DIR/outputs"

if [[ ! -f "$TOKENS_FILE" ]]; then
  echo "ERROR: tokens.json not found at $TOKENS_FILE" >&2
  exit 1
fi

mkdir -p "$OUTPUT_DIR"

python3 - "$TOKENS_FILE" "$OUTPUT_DIR" <<'PYEOF'
import sys
import json
import math
import re
from pathlib import Path
from datetime import datetime, timezone

tokens_path = Path(sys.argv[1])
output_dir  = Path(sys.argv[2])

# ---------------------------------------------------------------------------
# Load tokens
# ---------------------------------------------------------------------------
with tokens_path.open() as f:
    data = json.load(f)

# Remove $schema key if present
data.pop("$schema", None)

# ---------------------------------------------------------------------------
# Flatten: walk nested DTCG token tree and collect (name, type, value) tuples
# ---------------------------------------------------------------------------
def flatten(node: dict, prefix: str = "") -> list[tuple[str, str, str]]:
    results = []
    for key, val in node.items():
        if key.startswith("$"):
            continue
        full_key = f"{prefix}-{key}" if prefix else key
        if isinstance(val, dict) and "$value" in val:
            token_type  = val.get("$type", "unknown")
            token_value = val["$value"]
            results.append((full_key, token_type, token_value))
        elif isinstance(val, dict):
            results.extend(flatten(val, full_key))
    return results

tokens = flatten(data)

# ---------------------------------------------------------------------------
# CSS custom-property name: convert to kebab, prefix with --
# e.g. "color-primary" -> "--color-primary"
# ---------------------------------------------------------------------------
def css_var(name: str) -> str:
    return f"--{name}"

# ---------------------------------------------------------------------------
# Generate tokens.css  (:root block)
# ---------------------------------------------------------------------------
timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

lines_root = [
    f"/* Auto-generated by build-tokens.sh on {timestamp} */",
    "/* Source: tokens/tokens.json (W3C DTCG format)   */",
    "/* DO NOT EDIT — regenerate with: bash tokens/build-tokens.sh */",
    "",
    ":root {",
]

by_group: dict[str, list[tuple[str, str, str]]] = {}
for name, ttype, value in tokens:
    group = name.split("-")[0]
    by_group.setdefault(group, []).append((name, ttype, value))

for group, group_tokens in by_group.items():
    lines_root.append(f"  /* {group} */")
    for name, ttype, value in group_tokens:
        lines_root.append(f"  {css_var(name)}: {value};")
    lines_root.append("")

lines_root.append("}")

css_path = output_dir / "tokens.css"
css_path.write_text("\n".join(lines_root) + "\n")

# ---------------------------------------------------------------------------
# Generate tailwind-theme.css  (Tailwind v4 @theme block)
# Tailwind v4 reads CSS custom properties from an @theme {} block.
# Convention: --color-*, --spacing-*, --radius-*, --font-*
# ---------------------------------------------------------------------------
lines_tw = [
    f"/* Auto-generated by build-tokens.sh on {timestamp} */",
    "/* Tailwind v4 @theme block — import this in your main CSS */",
    "/* DO NOT EDIT — regenerate with: bash tokens/build-tokens.sh */",
    "",
    "@theme {",
]

for group, group_tokens in by_group.items():
    lines_tw.append(f"  /* {group} */")
    for name, ttype, value in group_tokens:
        # Tailwind v4 naming: --color-primary, --spacing-md, etc.
        lines_tw.append(f"  {css_var(name)}: {value};")
    lines_tw.append("")

lines_tw.append("}")

tw_path = output_dir / "tailwind-theme.css"
tw_path.write_text("\n".join(lines_tw) + "\n")

# ---------------------------------------------------------------------------
# WCAG AA contrast check
# We use a simplified luminance approximation for oklch values.
# oklch(L C H) — relative luminance ≈ L^2.2 (perceptual lightness → linear)
# This is an approximation; for production, use a proper color-space library.
# ---------------------------------------------------------------------------
def oklch_lightness(value: str) -> float | None:
    """Extract the L component from an oklch(...) string."""
    m = re.match(r"oklch\(\s*([\d.]+)", value)
    if m:
        return float(m.group(1))
    return None

def approx_relative_luminance(oklch_value: str) -> float | None:
    L = oklch_lightness(oklch_value)
    if L is None:
        return None
    # oklch L is roughly perceptual lightness (0–1).
    # Approximate linear luminance via gamma: Y ≈ L^2.2
    return L ** 2.2

def contrast_ratio(lum1: float, lum2: float) -> float:
    lighter = max(lum1, lum2)
    darker  = min(lum1, lum2)
    return (lighter + 0.05) / (darker + 0.05)

# Pairs to check: (label, foreground-token-name, background-token-name)
CONTRAST_PAIRS = [
    ("foreground / background",         "color-foreground",         "color-background"),
    ("primary-foreground / primary",     "color-primary-foreground", "color-primary"),
    ("muted-foreground / muted",         "color-muted-foreground",   "color-muted"),
    ("muted-foreground / background",    "color-muted-foreground",   "color-background"),
    ("destructive / background",         "color-destructive",        "color-background"),
    ("success / background",             "color-success",            "color-background"),
    ("warning / background",             "color-warning",            "color-background"),
    ("info / background",                "color-info",               "color-background"),
]

token_map = {name: value for name, _, value in tokens}

print("\n╔══════════════════════════════════════════════════════════╗")
print("║          W3C DTCG Token Build Summary                   ║")
print("╠══════════════════════════════════════════════════════════╣")
print(f"║  Source:  {str(tokens_path):<48}║")
print(f"║  Outputs: {str(output_dir):<48}║")
print("╠══════════════════════════════════════════════════════════╣")
print(f"║  Total tokens generated: {len(tokens):<34}║")

group_counts = {g: len(t) for g, t in by_group.items()}
for group, count in group_counts.items():
    label = f"    {group}"
    print(f"║  {label:<24}  {count} token(s){'':<25}║")

print("╠══════════════════════════════════════════════════════════╣")
print("║  WCAG AA Contrast Check (≥4.5:1 normal, ≥3:1 large)    ║")
print("║  [approx — based on oklch L channel]                    ║")
print("╠══════════════════════════════════════════════════════════╣")

all_pass = True
for label, fg_name, bg_name in CONTRAST_PAIRS:
    fg_val = token_map.get(fg_name)
    bg_val = token_map.get(bg_name)
    if fg_val is None or bg_val is None:
        print(f"║  SKIP  {label:<50}║")
        continue
    fg_lum = approx_relative_luminance(fg_val)
    bg_lum = approx_relative_luminance(bg_val)
    if fg_lum is None or bg_lum is None:
        print(f"║  SKIP  {label:<50}║")
        continue
    ratio = contrast_ratio(fg_lum, bg_lum)
    status = "PASS" if ratio >= 4.5 else ("LARGE" if ratio >= 3.0 else "FAIL")
    if status == "FAIL":
        all_pass = False
    ratio_str = f"{ratio:.2f}:1"
    row = f"  [{status}]  {label}  ({ratio_str})"
    # Pad to fit column width of 58 chars
    print(f"║{row:<58}║")

print("╠══════════════════════════════════════════════════════════╣")
overall = "ALL PAIRS PASS" if all_pass else "SOME PAIRS NEED REVIEW"
print(f"║  Contrast result: {overall:<40}║")
print("╠══════════════════════════════════════════════════════════╣")
print(f"║  tokens.css          -> outputs/tokens.css             ║")
print(f"║  tailwind-theme.css  -> outputs/tailwind-theme.css     ║")
print("╚══════════════════════════════════════════════════════════╝")
print()

PYEOF

echo "Build complete."
